class_name StateID

const IDLE           = "idle"
const MOVE           = "move"
const RUN            = "run"
const DASH           = "dash"
const BACKSTEP       = "backstep"
const DASH_REBOUND   = "dash_rebound"
const GRAB_IDLE      = "grab_idle"
const PUSHING        = "pushing"
const PULLING        = "pulling"
const BAT_TRAVEL     = "bat_travel"
const ATTACK         = "attack"
const NO_ACTION      = "no_action"
const INTERACT       = "interact"
const GRAB           = "grab"
const LIFT           = "lift"
const HOLDING_ACTION = "holding_action"
const THROW          = "throw"
const DROP           = "drop"

const KNOCKBACK      = "knockback"
const INITIALIZED    = "initialized"

# Enemy states
const ROAM           = "roam"
const CHASE          = "chase"
const COMBAT         = "combat"
const DAMAGED        = "damaged"
const DYING          = "dying"
const DEAD           = "dead"
const BLOCK          = "block"
const ENEMY_ATTACK   = "enemy_attack"
