class_name StateKeys

const IDLE           = "idle"
const MOVE           = "move"
const RUN            = "run"
const DASH           = "dash"
const BACKSTEP       = "backstep"
const DASH_REBOUND   = "dash_rebound"
const GRAB_IDLE      = "grab_idle"
const PUSHING        = "pushing"
const PULLING        = "pulling"
const BAT_TRAVEL     = "bat_travel"
const ATTACK         = "attack"
const NO_ACTION      = "no_action"
const INTERACT       = "interact"
const GRAB           = "grab"
const LIFT           = "lift"
const HOLDING_ACTION = "holding_action"
const THROW          = "throw"
const DROP           = "drop"
